[2024-10-14T04:21:43.959+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-14T04:21:44.021+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_ml_pipeline.ML_Kaggle scheduled__2024-10-13T02:00:00+00:00 [queued]>
[2024-10-14T04:21:44.034+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_ml_pipeline.ML_Kaggle scheduled__2024-10-13T02:00:00+00:00 [queued]>
[2024-10-14T04:21:44.037+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-14T04:21:44.075+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): ML_Kaggle> on 2024-10-13 02:00:00+00:00
[2024-10-14T04:21:44.121+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kaggle_ml_pipeline', 'ML_Kaggle', 'scheduled__2024-10-13T02:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/data/dmc_pipeline.py', '--cfg-path', '/tmp/tmpvto0lmt4']
[2024-10-14T04:21:44.113+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1378) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-14T04:21:44.134+0000] {standard_task_runner.py:72} INFO - Started process 2061 to run task
[2024-10-14T04:21:44.135+0000] {standard_task_runner.py:105} INFO - Job 21: Subtask ML_Kaggle
[2024-10-14T04:21:44.279+0000] {task_command.py:467} INFO - Running <TaskInstance: kaggle_ml_pipeline.ML_Kaggle scheduled__2024-10-13T02:00:00+00:00 [running]> on host 3865df127200
[2024-10-14T04:21:44.995+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_ml_pipeline' AIRFLOW_CTX_TASK_ID='ML_Kaggle' AIRFLOW_CTX_EXECUTION_DATE='2024-10-13T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-13T02:00:00+00:00'
[2024-10-14T04:21:44.999+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-14T04:21:45.000+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-14T04:21:45.001+0000] {logging_mixin.py:190} INFO - Current task name:ML_Kaggle state:running start_date:2024-10-14 04:21:44.021928+00:00
[2024-10-14T04:21:45.001+0000] {logging_mixin.py:190} INFO - Dag name:kaggle_ml_pipeline and current dag run status:running
[2024-10-14T04:21:45.004+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-14T04:21:46.208+0000] {warnings.py:112} WARNING - /opt/***/dags/data/dmc_pipeline.py:35: DtypeWarning: Columns (0,1,2,4,7,8,9,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data_path)

[2024-10-14T04:21:46.290+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data/dmc_pipeline.py", line 125, in ml_kaggle
    model = ml_system.train_kaggle(data_path=data_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data/dmc_pipeline.py", line 42, in train_kaggle
    label_encoder = LabelEncoder()
                    ^^^^^^^^^^^^
NameError: name 'LabelEncoder' is not defined
[2024-10-14T04:21:46.374+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-14T04:21:46.378+0000] {logging_mixin.py:190} INFO - Task start:2024-10-14 04:21:44.021928+00:00 end:2024-10-14 04:21:46.373393+00:00 duration:2.351465
[2024-10-14T04:21:46.380+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): ML_Kaggle> dag:<DAG: kaggle_ml_pipeline> dagrun:<DagRun kaggle_ml_pipeline @ 2024-10-13 02:00:00+00:00: scheduled__2024-10-13T02:00:00+00:00, state:running, queued_at: 2024-10-14 04:21:25.370663+00:00. externally triggered: False>
[2024-10-14T04:21:46.384+0000] {logging_mixin.py:190} INFO - Failure caused by name 'LabelEncoder' is not defined
[2024-10-14T04:21:46.390+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=kaggle_ml_pipeline, task_id=ML_Kaggle, run_id=scheduled__2024-10-13T02:00:00+00:00, execution_date=20241013T020000, start_date=20241014T042144, end_date=20241014T042146
[2024-10-14T04:21:46.602+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-14T04:21:46.604+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 21 for task ML_Kaggle (name 'LabelEncoder' is not defined; 2061)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data/dmc_pipeline.py", line 125, in ml_kaggle
    model = ml_system.train_kaggle(data_path=data_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data/dmc_pipeline.py", line 42, in train_kaggle
    label_encoder = LabelEncoder()
                    ^^^^^^^^^^^^
NameError: name 'LabelEncoder' is not defined
[2024-10-14T04:21:46.693+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-14T04:21:46.781+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-14T04:21:46.788+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-14T04:24:57.959+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-14T04:24:57.989+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_ml_pipeline.ML_Kaggle scheduled__2024-10-13T02:00:00+00:00 [queued]>
[2024-10-14T04:24:58.003+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_ml_pipeline.ML_Kaggle scheduled__2024-10-13T02:00:00+00:00 [queued]>
[2024-10-14T04:24:58.004+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-14T04:24:58.021+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): ML_Kaggle> on 2024-10-13 02:00:00+00:00
[2024-10-14T04:24:58.035+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3526) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-14T04:24:58.038+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kaggle_ml_pipeline', 'ML_Kaggle', 'scheduled__2024-10-13T02:00:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/data/dmc_pipeline.py', '--cfg-path', '/tmp/tmpuj4r7z2p']
[2024-10-14T04:24:58.038+0000] {standard_task_runner.py:72} INFO - Started process 3798 to run task
[2024-10-14T04:24:58.039+0000] {standard_task_runner.py:105} INFO - Job 57: Subtask ML_Kaggle
[2024-10-14T04:24:58.109+0000] {task_command.py:467} INFO - Running <TaskInstance: kaggle_ml_pipeline.ML_Kaggle scheduled__2024-10-13T02:00:00+00:00 [running]> on host 3865df127200
[2024-10-14T04:24:58.228+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_ml_pipeline' AIRFLOW_CTX_TASK_ID='ML_Kaggle' AIRFLOW_CTX_EXECUTION_DATE='2024-10-13T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-13T02:00:00+00:00'
[2024-10-14T04:24:58.231+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-14T04:24:58.232+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-14T04:24:58.234+0000] {logging_mixin.py:190} INFO - Current task name:ML_Kaggle state:running start_date:2024-10-14 04:24:57.990307+00:00
[2024-10-14T04:24:58.235+0000] {logging_mixin.py:190} INFO - Dag name:kaggle_ml_pipeline and current dag run status:running
[2024-10-14T04:24:58.235+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-14T04:24:58.879+0000] {warnings.py:112} WARNING - /opt/***/dags/data/dmc_pipeline.py:36: DtypeWarning: Columns (0,1,2,4,7,8,9,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data_path)

[2024-10-14T04:24:59.143+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_encode.py", line 174, in _unique_python
    uniques = sorted(uniques_set)
              ^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'int' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data/dmc_pipeline.py", line 126, in ml_kaggle
    model = ml_system.train_kaggle(data_path=data_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data/dmc_pipeline.py", line 46, in train_kaggle
    X[col]=label_encoder.fit_transform(X[col])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_label.py", line 115, in fit_transform
    self.classes_, y = _unique(y, return_inverse=True)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_encode.py", line 42, in _unique
    return _unique_python(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_encode.py", line 179, in _unique_python
    raise TypeError(
TypeError: Encoders require their input argument must be uniformly strings or numbers. Got ['int', 'str']
[2024-10-14T04:24:59.170+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-14T04:24:59.171+0000] {logging_mixin.py:190} INFO - Task start:2024-10-14 04:24:57.990307+00:00 end:2024-10-14 04:24:59.168444+00:00 duration:1.178137
[2024-10-14T04:24:59.171+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): ML_Kaggle> dag:<DAG: kaggle_ml_pipeline> dagrun:<DagRun kaggle_ml_pipeline @ 2024-10-13 02:00:00+00:00: scheduled__2024-10-13T02:00:00+00:00, state:running, queued_at: 2024-10-14 04:24:47.705577+00:00. externally triggered: False>
[2024-10-14T04:24:59.172+0000] {logging_mixin.py:190} INFO - Failure caused by Encoders require their input argument must be uniformly strings or numbers. Got ['int', 'str']
[2024-10-14T04:24:59.172+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=kaggle_ml_pipeline, task_id=ML_Kaggle, run_id=scheduled__2024-10-13T02:00:00+00:00, execution_date=20241013T020000, start_date=20241014T042457, end_date=20241014T042459
[2024-10-14T04:24:59.682+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-14T04:24:59.683+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 57 for task ML_Kaggle (Encoders require their input argument must be uniformly strings or numbers. Got ['int', 'str']; 3798)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_encode.py", line 174, in _unique_python
    uniques = sorted(uniques_set)
              ^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'int' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data/dmc_pipeline.py", line 126, in ml_kaggle
    model = ml_system.train_kaggle(data_path=data_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data/dmc_pipeline.py", line 46, in train_kaggle
    X[col]=label_encoder.fit_transform(X[col])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_label.py", line 115, in fit_transform
    self.classes_, y = _unique(y, return_inverse=True)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_encode.py", line 42, in _unique
    return _unique_python(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_encode.py", line 179, in _unique_python
    raise TypeError(
TypeError: Encoders require their input argument must be uniformly strings or numbers. Got ['int', 'str']
[2024-10-14T04:24:59.768+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-14T04:24:59.806+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-14T04:24:59.817+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
