[2024-10-14T04:21:44.054+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-14T04:21:44.129+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_ml_pipeline.ML_Kaggle scheduled__2024-10-13T09:00:00+00:00 [queued]>
[2024-10-14T04:21:44.174+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_ml_pipeline.ML_Kaggle scheduled__2024-10-13T09:00:00+00:00 [queued]>
[2024-10-14T04:21:44.177+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-14T04:21:44.236+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): ML_Kaggle> on 2024-10-13 09:00:00+00:00
[2024-10-14T04:21:44.298+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1377) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-14T04:21:44.301+0000] {standard_task_runner.py:72} INFO - Started process 2065 to run task
[2024-10-14T04:21:44.307+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kaggle_ml_pipeline', 'ML_Kaggle', 'scheduled__2024-10-13T09:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/data/dmc_pipeline.py', '--cfg-path', '/tmp/tmpeyj_im_o']
[2024-10-14T04:21:44.311+0000] {standard_task_runner.py:105} INFO - Job 22: Subtask ML_Kaggle
[2024-10-14T04:21:44.438+0000] {task_command.py:467} INFO - Running <TaskInstance: kaggle_ml_pipeline.ML_Kaggle scheduled__2024-10-13T09:00:00+00:00 [running]> on host 3865df127200
[2024-10-14T04:21:45.292+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_ml_pipeline' AIRFLOW_CTX_TASK_ID='ML_Kaggle' AIRFLOW_CTX_EXECUTION_DATE='2024-10-13T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-13T09:00:00+00:00'
[2024-10-14T04:21:45.300+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-14T04:21:45.309+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-14T04:21:45.314+0000] {logging_mixin.py:190} INFO - Current task name:ML_Kaggle state:running start_date:2024-10-14 04:21:44.133631+00:00
[2024-10-14T04:21:45.316+0000] {logging_mixin.py:190} INFO - Dag name:kaggle_ml_pipeline and current dag run status:running
[2024-10-14T04:21:45.316+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-14T04:21:46.613+0000] {warnings.py:112} WARNING - /opt/***/dags/data/dmc_pipeline.py:35: DtypeWarning: Columns (0,1,2,4,7,8,9,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data_path)

[2024-10-14T04:21:46.693+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data/dmc_pipeline.py", line 125, in ml_kaggle
    model = ml_system.train_kaggle(data_path=data_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data/dmc_pipeline.py", line 42, in train_kaggle
    label_encoder = LabelEncoder()
                    ^^^^^^^^^^^^
NameError: name 'LabelEncoder' is not defined
[2024-10-14T04:21:46.754+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-14T04:21:46.763+0000] {logging_mixin.py:190} INFO - Task start:2024-10-14 04:21:44.133631+00:00 end:2024-10-14 04:21:46.753395+00:00 duration:2.619764
[2024-10-14T04:21:46.764+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): ML_Kaggle> dag:<DAG: kaggle_ml_pipeline> dagrun:<DagRun kaggle_ml_pipeline @ 2024-10-13 09:00:00+00:00: scheduled__2024-10-13T09:00:00+00:00, state:running, queued_at: 2024-10-14 04:21:26.575739+00:00. externally triggered: False>
[2024-10-14T04:21:46.765+0000] {logging_mixin.py:190} INFO - Failure caused by name 'LabelEncoder' is not defined
[2024-10-14T04:21:46.766+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=kaggle_ml_pipeline, task_id=ML_Kaggle, run_id=scheduled__2024-10-13T09:00:00+00:00, execution_date=20241013T090000, start_date=20241014T042144, end_date=20241014T042146
[2024-10-14T04:21:46.823+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-14T04:21:46.824+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 22 for task ML_Kaggle (name 'LabelEncoder' is not defined; 2065)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data/dmc_pipeline.py", line 125, in ml_kaggle
    model = ml_system.train_kaggle(data_path=data_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data/dmc_pipeline.py", line 42, in train_kaggle
    label_encoder = LabelEncoder()
                    ^^^^^^^^^^^^
NameError: name 'LabelEncoder' is not defined
[2024-10-14T04:21:46.944+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-14T04:21:47.009+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-14T04:21:47.017+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-14T04:25:02.512+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-14T04:25:02.552+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_ml_pipeline.ML_Kaggle scheduled__2024-10-13T09:00:00+00:00 [queued]>
[2024-10-14T04:25:02.569+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_ml_pipeline.ML_Kaggle scheduled__2024-10-13T09:00:00+00:00 [queued]>
[2024-10-14T04:25:02.573+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-14T04:25:02.598+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): ML_Kaggle> on 2024-10-13 09:00:00+00:00
[2024-10-14T04:25:02.622+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3968) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-14T04:25:02.625+0000] {standard_task_runner.py:72} INFO - Started process 4320 to run task
[2024-10-14T04:25:02.636+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kaggle_ml_pipeline', 'ML_Kaggle', 'scheduled__2024-10-13T09:00:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/data/dmc_pipeline.py', '--cfg-path', '/tmp/tmpylhhmyqj']
[2024-10-14T04:25:02.638+0000] {standard_task_runner.py:105} INFO - Job 64: Subtask ML_Kaggle
[2024-10-14T04:25:02.784+0000] {task_command.py:467} INFO - Running <TaskInstance: kaggle_ml_pipeline.ML_Kaggle scheduled__2024-10-13T09:00:00+00:00 [running]> on host 3865df127200
[2024-10-14T04:25:03.346+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_ml_pipeline' AIRFLOW_CTX_TASK_ID='ML_Kaggle' AIRFLOW_CTX_EXECUTION_DATE='2024-10-13T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-13T09:00:00+00:00'
[2024-10-14T04:25:03.347+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-14T04:25:03.348+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-14T04:25:03.349+0000] {logging_mixin.py:190} INFO - Current task name:ML_Kaggle state:running start_date:2024-10-14 04:25:02.553436+00:00
[2024-10-14T04:25:03.349+0000] {logging_mixin.py:190} INFO - Dag name:kaggle_ml_pipeline and current dag run status:running
[2024-10-14T04:25:03.350+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-14T04:25:03.986+0000] {warnings.py:112} WARNING - /opt/***/dags/data/dmc_pipeline.py:36: DtypeWarning: Columns (0,1,2,4,7,8,9,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data_path)

[2024-10-14T04:25:04.229+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_encode.py", line 174, in _unique_python
    uniques = sorted(uniques_set)
              ^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'int' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data/dmc_pipeline.py", line 126, in ml_kaggle
    model = ml_system.train_kaggle(data_path=data_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data/dmc_pipeline.py", line 46, in train_kaggle
    X[col]=label_encoder.fit_transform(X[col])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_label.py", line 115, in fit_transform
    self.classes_, y = _unique(y, return_inverse=True)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_encode.py", line 42, in _unique
    return _unique_python(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_encode.py", line 179, in _unique_python
    raise TypeError(
TypeError: Encoders require their input argument must be uniformly strings or numbers. Got ['int', 'str']
[2024-10-14T04:25:04.257+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-14T04:25:04.258+0000] {logging_mixin.py:190} INFO - Task start:2024-10-14 04:25:02.553436+00:00 end:2024-10-14 04:25:04.256797+00:00 duration:1.703361
[2024-10-14T04:25:04.259+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): ML_Kaggle> dag:<DAG: kaggle_ml_pipeline> dagrun:<DagRun kaggle_ml_pipeline @ 2024-10-13 09:00:00+00:00: scheduled__2024-10-13T09:00:00+00:00, state:running, queued_at: 2024-10-14 04:24:49.298428+00:00. externally triggered: False>
[2024-10-14T04:25:04.259+0000] {logging_mixin.py:190} INFO - Failure caused by Encoders require their input argument must be uniformly strings or numbers. Got ['int', 'str']
[2024-10-14T04:25:04.260+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=kaggle_ml_pipeline, task_id=ML_Kaggle, run_id=scheduled__2024-10-13T09:00:00+00:00, execution_date=20241013T090000, start_date=20241014T042502, end_date=20241014T042504
[2024-10-14T04:25:04.281+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-14T04:25:04.282+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 64 for task ML_Kaggle (Encoders require their input argument must be uniformly strings or numbers. Got ['int', 'str']; 4320)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_encode.py", line 174, in _unique_python
    uniques = sorted(uniques_set)
              ^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'int' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data/dmc_pipeline.py", line 126, in ml_kaggle
    model = ml_system.train_kaggle(data_path=data_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data/dmc_pipeline.py", line 46, in train_kaggle
    X[col]=label_encoder.fit_transform(X[col])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_label.py", line 115, in fit_transform
    self.classes_, y = _unique(y, return_inverse=True)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_encode.py", line 42, in _unique
    return _unique_python(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_encode.py", line 179, in _unique_python
    raise TypeError(
TypeError: Encoders require their input argument must be uniformly strings or numbers. Got ['int', 'str']
[2024-10-14T04:25:04.364+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-14T04:25:04.400+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-14T04:25:04.402+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
